# Copyright 2023 Vivaldi Technologies. All rights reserved.

source_set("service") {
  sources = [
    "vivaldi_thumbnail_capturer.h",
    "vivaldi_thumbnail_capturer.mm",
    "vivaldi_thumbnail_capturer_provider.h",
    "vivaldi_thumbnail_capturer_provider.mm",
    "vivaldi_thumbnail_service.h",
    "vivaldi_thumbnail_service.mm",
  ]

  deps = [
    "//base",
    "//ui/base",
    "//components/bookmarks/browser",
  ]

  frameworks = [
    "ImageIO.framework",
    "UIKit.framework",
    "WebKit.framework",
  ]
}
