import("//build/config/ui.gni")
import("//extensions/buildflags/buildflags.gni")
import ("//vivaldi/testing/testing.gni")

if (!is_android && !is_mac) {
  update_target("//chrome:chrome_initial") {
    if (is_linux && current_cpu == "x86") {
      ldflags += [
        "-z",
        "notext",
      ]
    }
  }
}

if (is_win) {
  update_target("//chrome:chrome_dll") {
    deps += [
      "//vivaldi/browser",
    ]
  }

  update_target("//chrome:chrome_initial") {
    data_deps -= [
      "//chrome/chrome_proxy",
      "//chrome/elevation_service",
    ]
    data_deps += [ "//vivaldi/tools/vivaldi_proxy" ]
  }
}

update_target("//chrome:dependencies") {
  public_deps += [
    "//vivaldi/browser",
  ]
}

if (is_android) {
  update_target("//chrome:chrome_android_core") {
    deps += [
      "//vivaldi/browser",
    ]
  }
}

update_target("//chrome/browser:browser") {
  public_deps += [
    "//vivaldi/browser",
    "//vivaldi/browser/ad_blocker",
    "//vivaldi/browser/kagi_token",
    "//vivaldi/browser:features",
    "//vivaldi/browser:internal_handlers",
    "//vivaldi/browser:removed_partners_tracker",
    "//vivaldi/components:tabs",
  ]
  allow_circular_includes_from += [
    "//vivaldi/browser",
  ]
  configs += [
     "//vivaldi/gn/config:release_kind"
  ]

  if (!is_android) {
    deps -= [
      "//chrome/browser/default_browser",
      "//chrome/browser/ui/startup/default_browser_prompt",
      "//chrome/browser/ui/startup/default_browser_prompt:impl",
      "//chrome/browser/ui/webui/default_browser:default_browser_modal",
      "//chrome/browser/ui/webui/default_browser:modal_mojo_bindings",
    ]
    allow_circular_includes_from -= [
      "//chrome/browser/ui/startup/default_browser_prompt:impl",
    ]
  }
  if (is_win || is_mac) {
    deps -= [
      "//chrome/browser/ui/startup/default_browser_prompt/pin_infobar:impl",
    ]
    allow_circular_includes_from -= [
      "//chrome/browser/ui/startup/default_browser_prompt/pin_infobar:impl",
    ]
  }
}

if (!is_android) {
  update_target("//chrome/browser/ui/toolbar:impl") {
    deps -= [
      "//chrome/browser/ui/startup/default_browser_prompt",
    ]
  }

  update_target("//chrome/browser/ui/webui:configs") {
    deps -= [
      "//chrome/browser/ui/webui/default_browser:default_browser_modal",
    ]
  }

  update_target("//chrome/browser/ui/webui/infobar_internals:impl") {
    deps -= [
      "//chrome/browser/ui/startup/default_browser_prompt",
    ]
  }

  update_target("//chrome/browser/resources:resources") {
    public_deps -= [
       "default_browser/default_browser_modal:resources",
    ]
  }
}

update_target("//chrome/browser/ui:ui") {
  public_deps += [
    "//components/sessions:sessions",
    "//vivaldi/browser",
    "//vivaldi/prefs:prefs_strings",
  ]
  if (is_mac) {
    public_deps += [ "//vivaldi/browser:init_sparkle" ]
  }
  allow_circular_includes_from += [
    "//vivaldi/browser",
  ]
  if (enable_extensions) {
    allow_circular_includes_from += [
      "//components/guest_view/browser",
    ]
  }
  deps += [
    "//chrome/services/sharing/public/proto",
  ]
}

update_target("//content/browser:browser") {
  if (ozone_platform_x11) {
    public_deps += [ "//ui/events/keycodes:x11" ]
  }
  public_deps += [ "//vivaldi/browser:clipboard" ]
}

update_target("//components/input:input") {
  public_deps += [ "//vivaldi/browser:clipboard" ]
}

if (!is_android) {
#  update_target("//chrome/browser/password_manager/actor_login/internal:delegate") {
#    deps += [
#      "//components/paint_preview/buildflags",
#      "//pdf:buildflags",
#    ]
#  }

  update_target("//chrome/browser/safe_browsing:safe_browsing") {
    deps += [
      "//components/themes:ntp_background_proto",
    ]
  }
}
