update_target("//chrome/renderer:renderer") {
  deps += [
    "//third_party/highway:libhwy",
    "//vivaldi/renderer/mojo:frame_service",
    "//vivaldi/ui:skia_utils",
  ]
}

if (!is_android) {
  update_target("//extensions/browser:browser_sources") {
    deps += [ "//vivaldi/renderer/mojo:frame_service" ]
  }
}
