# Copyright (c) 2015-2017 Vivaldi Technologies AS. All rights reserved

update_target("//components/sync_sessions:sync_sessions") {
  deps += [ "//vivaldi/prefs:prefs_files_generated" ]
}

update_target("//components/sync/base:base") {
  configs += [ "//vivaldi/gn/config:release_kind" ]
}
update_target("//components/sync/engine:engine") {
  deps += [ "//vivaldi/sync/test:fake_server" ]
}
