# Copyright (c) 2025 Vivaldi Technologies AS. All rights reserved

import("//build/config/ios/rules.gni")

bundle_data_xcassets("assets") {
  catalog = "Assets.xcassets"
  sources = [
    # reader_view_animation_color
    # readerview_settings_icon
    "Assets.xcassets/reader_view_animation.colorset/Contents.json",
    "Assets.xcassets/readerview_settings.imageset/Contents.json",
    "Assets.xcassets/readerview_settings.imageset/readerview_settings.pdf",
  ]
}
