
deps_desk_andr_update_deps_list = [
  "//chrome/browser:browser",
  "//chrome/browser/actor:impl",
  "//chrome/browser/ai:ai",
  "//chrome/browser/contextual_tasks:impl",
  "//chrome/browser/contextual_tasks:ui_impl",
  "//chrome/browser/enterprise/data_controls:data_controls",
  "//chrome/browser/password_manager/actor_login/internal:internal",
  "//chrome/browser/prefs:impl",
  "//chrome/browser/profiles:profiles_extra_parts_impl",
  "//chrome/browser/sessions:sessions",
  "//chrome/browser/skills:skills",
  "//chrome/browser/sync:sync",
  "//chrome/browser/task_manager:impl",
  "//chrome/browser/ui:tab_search_feature",
  "//chrome/browser/ui:ui",
  "//chrome/browser/ui/webui:configs",
]

deps_desk_andr_update_deps_templ_list = [
  "//chrome/browser/media/webrtc:webrtc",
]

update_target("//chrome/browser/resources:resources") {
  public_deps -= [
    "glic:resources",
    "glic/fre:resources",
    "glic/shared:resources",
  ]
  if (!is_android) {
    public_deps -= [
      "glic/selection_overlay:resources",
    ]
  }
}
