
update_target("//chrome/browser:browser") {
  sources -= [
    "glic/suggestions/contextual_cueing_helper.cc",
    "glic/suggestions/contextual_cueing_service.cc",
    "glic/suggestions/contextual_cueing_service.h",
    "glic/suggestions/contextual_cueing_service_factory.cc",
  ]
}

update_target("//chrome/browser/skills:skills") {
  sources -= [
    "skills_glic_mojom_util.cc",
  ]
}