update_target("//chrome/browser/skills:skills") {
  sources -= [ "skills_glic_mojom_util.cc" ]
}

update_template_instance("//chrome/browser/ui/android/actions:java") {
  sources -= [
    "java/src/org/chromium/chrome/browser/ui/actions/glic/GlicActionButtonBinder.java",
    "java/src/org/chromium/chrome/browser/ui/actions/glic/GlicActionCoordinator.java",
    "java/src/org/chromium/chrome/browser/ui/actions/glic/GlicActionProperties.java",
    "java/src/org/chromium/chrome/browser/ui/actions/glic/GlicActionUtils.java",
  ]
}
