update_target("//chrome/browser:browser") {
  sources -= []
}

update_target("//chrome/browser/ui:ui") {
  sources -= [
    "views/profiles/feature_showcase/gemini_step_eligibility_checker.cc",
    "views/profiles/feature_showcase/gemini_step_eligibility_checker.h",
    "views/tabs/tab_strip_action_container.cc",
    "views/tabs/tab_strip_action_container.h",
  ]
}

update_target("//chrome/browser/ui/webui/settings:impl") {
  sources -= [ "glic_handler.cc" ]
}

update_target("//chrome/browser/ui/views/toolbar:impl") {
  sources -= [
    "toolbar_glic_actor_task_icon.cc",
    "toolbar_glic_button.cc",
  ]
}

update_target("//chrome/browser/ui/webui/feature_showcase:feature_showcase") {
  sources -= [
    "gemini_handler.cc",
    "gemini_handler.h",
  ]
}

update_template_instance("//chrome/browser/resources/settings:build") {
  web_component_files -= [
    "ai_page/ai_info_card.ts",
    "ai_page/ai_logging_info_bullet.ts",
    "ai_page/ai_mode_search_page.ts",
    "ai_page/ai_page.ts",
    "ai_page/ai_page_index.ts",
    "ai_page/ai_policy_indicator.ts",
    "ai_page/ai_site_add_dialog.ts",
    "ai_page/ai_suggestions_page.ts",
    "ai_page/history_search_page.ts",
    "ai_page/offer_writing_help_page.ts",
    "ai_page/skills_page.ts",
    "autofill_page/autofill_ai_add_or_edit_dialog.ts",
    "autofill_page/autofill_ai_entries_list.ts",
    "autofill_page/autofill_ai_section.ts",
    "glic_page/glic_page.ts",
    "glic_page/glic_login_permissions_page.ts",
    "glic_page/glic_subpage.ts",
    "privacy_page/privacy_guide/privacy_guide_completion_fragment.ts",
    "privacy_page/privacy_guide/privacy_guide_cookies_fragment.ts",
    "privacy_page/privacy_guide/privacy_guide_dialog.ts",
    "privacy_page/privacy_guide/privacy_guide_history_sync_fragment.ts",
    "privacy_page/privacy_guide/privacy_guide_msbb_fragment.ts",
    "privacy_page/privacy_guide/privacy_guide_page.ts",
    "privacy_page/privacy_guide/privacy_guide_promo.ts",
    "privacy_page/privacy_guide/privacy_guide_safe_browsing_fragment.ts",
    "privacy_page/privacy_guide/privacy_guide_welcome_fragment.ts",
    "privacy_page/privacy_guide/step_indicator.ts",
    "search_page/search_engines_page.ts",
    "search_page/search_page_index.ts",
    "search_page/search_page.ts",
  ]

  ts_files -= [
    "glic_page/glic_browser_proxy.ts",
    "privacy_page/privacy_guide/constants.ts",

    #"privacy_page/privacy_guide/privacy_guide_availability_mixin.ts",
    "privacy_page/privacy_guide/privacy_guide_browser_proxy.ts",
  ]
}

update_target("//chrome/browser/ui/omnibox:impl") {
  sources -= [ "ai_mode_page_action_controller.cc" ]
}

update_target("//chrome/browser/ui/tabs:tab_menu_impl") {
  sources -= [ "glic_tab_sub_menu_model.cc" ]
}

update_target("//chrome/browser/ui/tabs:tab_menu") {
  sources -= [ "glic_tab_sub_menu_model.h" ]
}

update_template_instance("//chrome/browser/extensions/api:api_registration") {
  sources -= [
    "//chrome/common/extensions/api/experimental_actor.webidl",
    "//chrome/common/extensions/api/experimental_ai_data.webidl",
    "//chrome/common/extensions/api/glic_private.webidl",
  ]
}

update_target("//chrome/browser/ui/tabs/organizer:impl") {
  sources -= [ "organizer_panel_state_controller.cc" ]
}

update_target("//chrome/browser/skills:skills") {
  sources -= [ "skills_glic_mojom_util.cc" ]
}

update_target("//chrome/browser/skills:ui") {
  sources -= [ "skills_dialog_launcher.cc" ]
}
