source_set("tools") {
  sources = [
    "../tools/vivaldi_tools.cpp",
    "../tools/vivaldi_tools.h",
  ]
  deps = [
    "//chrome/browser/ui/webui/tab_search:mojo_bindings",
    "//chrome/common",
    "//components/browser_apis/browser_controls:mojom_data_model_shared_cpp_sources",
    "//components/browser_apis/ui_controllers/toolbar:extensions_bar_data_model_mojom",
    "//components/browser_apis/ui_controllers/toolbar:icon_handle_mojom",
    "//components/browser_apis/ui_controllers/toolbar:mojom_data_model",
    "//components/sharing_message/proto",
    "//components/zoom",
    "//extensions/buildflags",

    # "//extensions/browser",
    "//net",
    "//skia",
    "//ui/views:buildflags",

    # "//vivaldi/ui",
  ]
}
