# Copyright 2023 Vivaldi Technologies. All rights reserved.

import("//build/config/apple/swift_source_set.gni")

# Notification constants - no dependencies, can be imported by anyone
source_set("wallpaper_notification_constants") {
  sources = [
    "vivaldi_wallpaper_notification_constants.h",
    "vivaldi_wallpaper_notification_constants.mm",
  ]

  frameworks = [ "Foundation.framework" ]
}

source_set("wallpaper_settings") {
  deps = [
    ":wallpaper_notification_constants",
    ":wallpaper_settings_swift",
    "resources:assets",
    "resources:wallpaper_assets",
    "//base",
    "//ui/base",
  ]

  frameworks = [
    "Foundation.framework",
    "UIKit.framework",
  ]
}

swift_source_set("wallpaper_settings_swift") {
  bridge_header = "vivaldi_wallpaper_settings_swift_bridge.h"
  sources = [
    "vivaldi_wallapaper_settings_constants.swift",
    "vivaldi_wallpaper_image_picker.swift",
    "vivaldi_wallpaper_navigation_bar.swift",
    "vivaldi_wallpaper_preview_representation.swift",
    "vivaldi_wallpaper_preview_viewcontroller.swift",
    "vivaldi_wallpaper_settings_view.swift",
    "vivaldi_wallpaper_settings_view_provider.swift",
    "vivaldi_wallpaper_thumbnail_image.swift",
    "vivaldi_wallpaper_thumbnail_modifier.swift",
    "vivaldi_wallpapers.swift",
  ]

  deps = [
    ":wallpaper_notification_constants",
    "//base",
    "//ios/chrome/app/strings",
    "//ui/base",
    "//url",
    "//vivaldi/ios/ui/helpers:helpers_swift",
    "//vivaldi/ios/ui/ntp:vivaldi_ntp",
    "//vivaldi/ios/ui/settings/start_page:start_page_constants",
  ]

  frameworks = [
    "Foundation.framework",
    "UIKit.framework",
    "SwiftUI.framework",
  ]
}
