# Copyright (c) 2026 Vivaldi Technologies AS. All rights reserved

source_set("vivaldi_policy_handlers") {
  sources = [
    "vivaldi_policy_handlers.cc",
    "vivaldi_policy_handlers.h",
  ]
  if (!is_android) {
    sources += [
      "vivaldi_vpn_policy_handler.cc",
      "vivaldi_vpn_policy_handler.h",
    ]
  }
  deps = [
    "//base",
    "//components/policy:generated",
    "//components/policy/core/browser",
    "//components/policy/core/common",
    "//components/prefs",
    "//components/strings",
  ]
  if (!is_android) {
    deps += [ "//vivaldi/prefs:prefs_files_generator" ]
  }
}
