static_library("ios") {
  sources = [
    "adblock_content_injection_handler.h",
    "adblock_content_injection_handler.mm",
    "adblock_content_rule_list_provider.h",
    "adblock_content_rule_list_provider.mm",
    "adblock_organized_rules_manager.cc",
    "adblock_organized_rules_manager.h",
    "adblock_rule_service_impl.cc",
    "adblock_rule_service_impl.h",
    "adblock_rules_organizer.cc",
    "adblock_rules_organizer.h",
  ]

  public_deps = [ "//vivaldi/components/ad_blocker/public/ios" ]

  deps = [
    ":rules_compiler",
    ":utils",
    "//base",
    "//components/keyed_service/core",
    "//ios/web/public",
    "//ios/web/web_state/ui:wk_web_view_configuration_provider",
    "//vivaldi/components/ad_blocker/core",
  ]
}

source_set("utils") {
  sources = [
    "ios_rule_utils.cc",
    "ios_rule_utils.h",
    "utils.cc",
    "utils.h",
  ]

  deps = [ "//base" ]
}

source_set("rules_compiler") {
  sources = [
    "ios_rules_compiler.cc",
    "ios_rules_compiler.h",
  ]

  public_deps = [ "//vivaldi/components/ad_blocker/core/parser" ]

  deps = [
    ":utils",
    "//base",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [
    "adblock_rules_organizer_unittest.cc",
    "ios_rules_compiler_unittest.cc",
  ]

  deps = [
    ":ios",
    "//base",
    "//testing/gtest",
  ]
}
