# Copyright 2022 Vivaldi Technologies. All rights reserved.

source_set("settings") {
  sources = [
    "vivaldi_atb_add_domain_source_view_controller.h",
    "vivaldi_atb_add_domain_source_view_controller.mm",
    "vivaldi_atb_per_site_settings_view_controller.h",
    "vivaldi_atb_per_site_settings_view_controller.mm",
    "vivaldi_atb_settings_view_controller.h",
    "vivaldi_atb_settings_view_controller.mm",
    "vivaldi_atb_source_settings_view_controller.h",
    "vivaldi_atb_source_settings_view_controller.mm",
  ]

  deps = [
    "//base",
    "//base:i18n",
    "//ios/chrome/app/strings",
    "//ios/chrome/common/ui/util",
    "//ui/base",
    "//vivaldi/ios/ui/settings:vivaldi_settings_common",
  ]

  frameworks = [
    "Foundation.framework",
    "UIKit.framework",
  ]
}
