# Copyright (c) 2019 Vivaldi Technologies AS. All rights reserved

static_library("content") {
  sources = [
    "adblock_content_injection_provider.cc",
    "adblock_content_injection_provider.h",
    "adblock_cosmetic_filter.cc",
    "adblock_cosmetic_filter.h",
    "adblock_document_state.cc",
    "adblock_document_state.h",
    "adblock_navigation_tracker_impl.cc",
    "adblock_navigation_tracker_impl.h",
    "adblock_request_filter.cc",
    "adblock_request_filter.h",
    "adblock_rule_service_impl.cc",
    "adblock_rule_service_impl.h",
    "adblock_state_and_logs_impl.cc",
    "adblock_state_and_logs_impl.h",
    "adblock_tab_state_and_logs_impl.cc",
    "adblock_tab_state_and_logs_impl.h",
    "simple_index_base_query.cc",
    "simple_index_base_query.h",
    "simple_index_request_query.cc",
    "simple_index_request_query.h",
  ]

  public_deps = [
    "//vivaldi/components/ad_blocker/content/index",
    "//vivaldi/components/ad_blocker/public/content",
  ]

  deps = [
    ":utils",
    "//base",
    "//base:i18n",
    "//components/keyed_service/content",
    "//content/public/browser",
    "//third_party/blink/public/common",
    "//url",
    "//vivaldi/components/ad_blocker/content/interstitial",
    "//vivaldi/components/ad_blocker/core",
    "//vivaldi/components/ad_blocker/core:parser",
    "//vivaldi/components/ad_blocker/public/content/mojom",
    "//vivaldi/components/content_injection",
    "//vivaldi/components/request_filter:request_filter_registry",
  ]
}

source_set("utils") {
  sources = [
    "utils.cc",
    "utils.h",
  ]

  deps = [
    "//base",
    "//url",
  ]
}
