#include "extensions/api/tabs_private/tests/unit_test_snapshots.h"

namespace vivaldi::test_snapshots {

std::set<std::string> PanelLinkAndConfigTabPosition() {
  return std::set<std::string>({
      "0;PanelLink;AlwaysLast;10",
      "0;PanelLink;DirectRightOfCurrent;1",
      "0;PanelLink;OpenInTabstackWithRelated;1",
      "0;PanelLink;RightOfCurrent;1",
      "0;PanelLinkBackground;AlwaysLast;10",
      "0;PanelLinkBackground;DirectRightOfCurrent;1",
      "0;PanelLinkBackground;OpenInTabstackWithRelated;1",
      "0;PanelLinkBackground;RightOfCurrent;1",
      "0;vivaldiUi;AlwaysLast;10",
      "0;vivaldiUi;DirectRightOfCurrent;1",
      "0;vivaldiUi;OpenInTabstackWithRelated;10",
      "0;vivaldiUi;RightOfCurrent;10",
      "2;PanelLink;AlwaysLast;10",
      "2;PanelLink;DirectRightOfCurrent;3",
      "2;PanelLink;OpenInTabstackWithRelated;3",
      "2;PanelLink;RightOfCurrent;3",
      "2;PanelLinkBackground;AlwaysLast;10",
      "2;PanelLinkBackground;DirectRightOfCurrent;3",
      "2;PanelLinkBackground;OpenInTabstackWithRelated;3",
      "2;PanelLinkBackground;RightOfCurrent;3",
      "2;vivaldiUi;AlwaysLast;10",
      "2;vivaldiUi;DirectRightOfCurrent;3",
      "2;vivaldiUi;OpenInTabstackWithRelated;10",
      "2;vivaldiUi;RightOfCurrent;10",
      "5;PanelLink;AlwaysLast;7",
      "5;PanelLink;DirectRightOfCurrent;6",
      "5;PanelLink;OpenInTabstackWithRelated;6",
      "5;PanelLink;RightOfCurrent;6",
      "5;PanelLinkBackground;AlwaysLast;7",
      "5;PanelLinkBackground;DirectRightOfCurrent;6",
      "5;PanelLinkBackground;OpenInTabstackWithRelated;6",
      "5;PanelLinkBackground;RightOfCurrent;6",
      "5;vivaldiUi;AlwaysLast;10",
      "5;vivaldiUi;DirectRightOfCurrent;7",
      "5;vivaldiUi;OpenInTabstackWithRelated;10",
      "5;vivaldiUi;RightOfCurrent;10",
  });
}

std::set<std::string> NewTabAllStrategies() {
  return std::set<std::string>({
      "0;O;Accordion;AlwaysLast;8",
      "0;O;Accordion;DirectRightOfCurrent;1",
      "0;O;Accordion;OpenInTabstackWithRelated;1",
      "0;O;Accordion;RightOfCurrent;1",
      "0;O;Dotted;AlwaysLast;8",
      "0;O;Dotted;DirectRightOfCurrent;1",
      "0;O;Dotted;OpenInTabstackWithRelated;1",
      "0;O;Dotted;RightOfCurrent;1",
      "0;O;Off;AlwaysLast;8",
      "0;O;Off;DirectRightOfCurrent;1",
      "0;O;Off;OpenInTabstackWithRelated;1",
      "0;O;Off;RightOfCurrent;1",
      "0;O;Substrip;AlwaysLast;8",
      "0;O;Substrip;DirectRightOfCurrent;1",
      "0;O;Substrip;OpenInTabstackWithRelated;1",
      "0;O;Substrip;RightOfCurrent;1",
      "0;OL;Accordion;AlwaysLast;8",
      "0;OL;Accordion;DirectRightOfCurrent;1",
      "0;OL;Accordion;OpenInTabstackWithRelated;1",
      "0;OL;Accordion;RightOfCurrent;1",
      "0;OL;Dotted;AlwaysLast;8",
      "0;OL;Dotted;DirectRightOfCurrent;1",
      "0;OL;Dotted;OpenInTabstackWithRelated;1",
      "0;OL;Dotted;RightOfCurrent;1",
      "0;OL;Off;AlwaysLast;8",
      "0;OL;Off;DirectRightOfCurrent;1",
      "0;OL;Off;OpenInTabstackWithRelated;1",
      "0;OL;Off;RightOfCurrent;1",
      "0;OL;Substrip;AlwaysLast;8",
      "0;OL;Substrip;DirectRightOfCurrent;1",
      "0;OL;Substrip;OpenInTabstackWithRelated;1",
      "0;OL;Substrip;RightOfCurrent;1",
      "0;X;Accordion;AlwaysLast;8",
      "0;X;Accordion;DirectRightOfCurrent;1",
      "0;X;Accordion;OpenInTabstackWithRelated;1",
      "0;X;Accordion;RightOfCurrent;1",
      "0;X;Dotted;AlwaysLast;8",
      "0;X;Dotted;DirectRightOfCurrent;1",
      "0;X;Dotted;OpenInTabstackWithRelated;1",
      "0;X;Dotted;RightOfCurrent;1",
      "0;X;Off;AlwaysLast;8",
      "0;X;Off;DirectRightOfCurrent;1",
      "0;X;Off;OpenInTabstackWithRelated;1",
      "0;X;Off;RightOfCurrent;1",
      "0;X;Substrip;AlwaysLast;8",
      "0;X;Substrip;DirectRightOfCurrent;1",
      "0;X;Substrip;OpenInTabstackWithRelated;1",
      "0;X;Substrip;RightOfCurrent;1",
      "0;XL;Accordion;AlwaysLast;8",
      "0;XL;Accordion;DirectRightOfCurrent;1",
      "0;XL;Accordion;OpenInTabstackWithRelated;1",
      "0;XL;Accordion;RightOfCurrent;1",
      "0;XL;Dotted;AlwaysLast;8",
      "0;XL;Dotted;DirectRightOfCurrent;1",
      "0;XL;Dotted;OpenInTabstackWithRelated;1",
      "0;XL;Dotted;RightOfCurrent;1",
      "0;XL;Off;AlwaysLast;8",
      "0;XL;Off;DirectRightOfCurrent;1",
      "0;XL;Off;OpenInTabstackWithRelated;1",
      "0;XL;Off;RightOfCurrent;1",
      "0;XL;Substrip;AlwaysLast;8",
      "0;XL;Substrip;DirectRightOfCurrent;1",
      "0;XL;Substrip;OpenInTabstackWithRelated;1",
      "0;XL;Substrip;RightOfCurrent;1",
      "1;O;Accordion;AlwaysLast;8",
      "1;O;Accordion;DirectRightOfCurrent;2",
      "1;O;Accordion;OpenInTabstackWithRelated;2",
      "1;O;Accordion;RightOfCurrent;2",
      "1;O;Dotted;AlwaysLast;8",
      "1;O;Dotted;DirectRightOfCurrent;2",
      "1;O;Dotted;OpenInTabstackWithRelated;2",
      "1;O;Dotted;RightOfCurrent;2",
      "1;O;Off;AlwaysLast;8",
      "1;O;Off;DirectRightOfCurrent;2",
      "1;O;Off;OpenInTabstackWithRelated;2",
      "1;O;Off;RightOfCurrent;2",
      "1;O;Substrip;AlwaysLast;8",
      "1;O;Substrip;DirectRightOfCurrent;2",
      "1;O;Substrip;OpenInTabstackWithRelated;2",
      "1;O;Substrip;RightOfCurrent;2",
      "1;OL;Accordion;AlwaysLast;8",
      "1;OL;Accordion;DirectRightOfCurrent;2",
      "1;OL;Accordion;OpenInTabstackWithRelated;2",
      "1;OL;Accordion;RightOfCurrent;2",
      "1;OL;Dotted;AlwaysLast;8",
      "1;OL;Dotted;DirectRightOfCurrent;2",
      "1;OL;Dotted;OpenInTabstackWithRelated;2",
      "1;OL;Dotted;RightOfCurrent;2",
      "1;OL;Off;AlwaysLast;8",
      "1;OL;Off;DirectRightOfCurrent;2",
      "1;OL;Off;OpenInTabstackWithRelated;2",
      "1;OL;Off;RightOfCurrent;2",
      "1;OL;Substrip;AlwaysLast;8",
      "1;OL;Substrip;DirectRightOfCurrent;2",
      "1;OL;Substrip;OpenInTabstackWithRelated;2",
      "1;OL;Substrip;RightOfCurrent;2",
      "1;X;Accordion;AlwaysLast;8",
      "1;X;Accordion;DirectRightOfCurrent;2",
      "1;X;Accordion;OpenInTabstackWithRelated;2",
      "1;X;Accordion;RightOfCurrent;2",
      "1;X;Dotted;AlwaysLast;8",
      "1;X;Dotted;DirectRightOfCurrent;2",
      "1;X;Dotted;OpenInTabstackWithRelated;2",
      "1;X;Dotted;RightOfCurrent;2",
      "1;X;Off;AlwaysLast;8",
      "1;X;Off;DirectRightOfCurrent;2",
      "1;X;Off;OpenInTabstackWithRelated;2",
      "1;X;Off;RightOfCurrent;2",
      "1;X;Substrip;AlwaysLast;8",
      "1;X;Substrip;DirectRightOfCurrent;2",
      "1;X;Substrip;OpenInTabstackWithRelated;2",
      "1;X;Substrip;RightOfCurrent;2",
      "1;XL;Accordion;AlwaysLast;8",
      "1;XL;Accordion;DirectRightOfCurrent;2",
      "1;XL;Accordion;OpenInTabstackWithRelated;2",
      "1;XL;Accordion;RightOfCurrent;2",
      "1;XL;Dotted;AlwaysLast;8",
      "1;XL;Dotted;DirectRightOfCurrent;2",
      "1;XL;Dotted;OpenInTabstackWithRelated;2",
      "1;XL;Dotted;RightOfCurrent;2",
      "1;XL;Off;AlwaysLast;8",
      "1;XL;Off;DirectRightOfCurrent;2",
      "1;XL;Off;OpenInTabstackWithRelated;2",
      "1;XL;Off;RightOfCurrent;2",
      "1;XL;Substrip;AlwaysLast;8",
      "1;XL;Substrip;DirectRightOfCurrent;2",
      "1;XL;Substrip;OpenInTabstackWithRelated;2",
      "1;XL;Substrip;RightOfCurrent;2",
      "4;O;Accordion;AlwaysLast;7",
      "4;O;Accordion;DirectRightOfCurrent;5",
      "4;O;Accordion;OpenInTabstackWithRelated;5",
      "4;O;Accordion;RightOfCurrent;5",
      "4;O;Dotted;AlwaysLast;7",
      "4;O;Dotted;DirectRightOfCurrent;5",
      "4;O;Dotted;OpenInTabstackWithRelated;5",
      "4;O;Dotted;RightOfCurrent;5",
      "4;O;Off;AlwaysLast;8",
      "4;O;Off;DirectRightOfCurrent;5",
      "4;O;Off;OpenInTabstackWithRelated;5",
      "4;O;Off;RightOfCurrent;5",
      "4;O;Substrip;AlwaysLast;7",
      "4;O;Substrip;DirectRightOfCurrent;5",
      "4;O;Substrip;OpenInTabstackWithRelated;5",
      "4;O;Substrip;RightOfCurrent;5",
      "4;OL;Accordion;AlwaysLast;7",
      "4;OL;Accordion;DirectRightOfCurrent;5",
      "4;OL;Accordion;OpenInTabstackWithRelated;5",
      "4;OL;Accordion;RightOfCurrent;5",
      "4;OL;Dotted;AlwaysLast;7",
      "4;OL;Dotted;DirectRightOfCurrent;5",
      "4;OL;Dotted;OpenInTabstackWithRelated;5",
      "4;OL;Dotted;RightOfCurrent;5",
      "4;OL;Off;AlwaysLast;8",
      "4;OL;Off;DirectRightOfCurrent;5",
      "4;OL;Off;OpenInTabstackWithRelated;5",
      "4;OL;Off;RightOfCurrent;5",
      "4;OL;Substrip;AlwaysLast;7",
      "4;OL;Substrip;DirectRightOfCurrent;5",
      "4;OL;Substrip;OpenInTabstackWithRelated;5",
      "4;OL;Substrip;RightOfCurrent;5",
      "4;X;Accordion;AlwaysLast;8",
      "4;X;Accordion;DirectRightOfCurrent;5",
      "4;X;Accordion;OpenInTabstackWithRelated;5",
      "4;X;Accordion;RightOfCurrent;5",
      "4;X;Dotted;AlwaysLast;8",
      "4;X;Dotted;DirectRightOfCurrent;5",
      "4;X;Dotted;OpenInTabstackWithRelated;5",
      "4;X;Dotted;RightOfCurrent;5",
      "4;X;Off;AlwaysLast;8",
      "4;X;Off;DirectRightOfCurrent;5",
      "4;X;Off;OpenInTabstackWithRelated;5",
      "4;X;Off;RightOfCurrent;5",
      "4;X;Substrip;AlwaysLast;8",
      "4;X;Substrip;DirectRightOfCurrent;5",
      "4;X;Substrip;OpenInTabstackWithRelated;5",
      "4;X;Substrip;RightOfCurrent;5",
      "4;XL;Accordion;AlwaysLast;8",
      "4;XL;Accordion;DirectRightOfCurrent;5",
      "4;XL;Accordion;OpenInTabstackWithRelated;5",
      "4;XL;Accordion;RightOfCurrent;5",
      "4;XL;Dotted;AlwaysLast;8",
      "4;XL;Dotted;DirectRightOfCurrent;5",
      "4;XL;Dotted;OpenInTabstackWithRelated;5",
      "4;XL;Dotted;RightOfCurrent;5",
      "4;XL;Off;AlwaysLast;8",
      "4;XL;Off;DirectRightOfCurrent;5",
      "4;XL;Off;OpenInTabstackWithRelated;5",
      "4;XL;Off;RightOfCurrent;5",
      "4;XL;Substrip;AlwaysLast;8",
      "4;XL;Substrip;DirectRightOfCurrent;5",
      "4;XL;Substrip;OpenInTabstackWithRelated;5",
      "4;XL;Substrip;RightOfCurrent;5",
      "5;O;Accordion;AlwaysLast;7",
      "5;O;Accordion;DirectRightOfCurrent;6",
      "5;O;Accordion;OpenInTabstackWithRelated;6",
      "5;O;Accordion;RightOfCurrent;6",
      "5;O;Dotted;AlwaysLast;7",
      "5;O;Dotted;DirectRightOfCurrent;6",
      "5;O;Dotted;OpenInTabstackWithRelated;6",
      "5;O;Dotted;RightOfCurrent;6",
      "5;O;Off;AlwaysLast;8",
      "5;O;Off;DirectRightOfCurrent;6",
      "5;O;Off;OpenInTabstackWithRelated;6",
      "5;O;Off;RightOfCurrent;6",
      "5;O;Substrip;AlwaysLast;7",
      "5;O;Substrip;DirectRightOfCurrent;6",
      "5;O;Substrip;OpenInTabstackWithRelated;6",
      "5;O;Substrip;RightOfCurrent;6",
      "5;OL;Accordion;AlwaysLast;7",
      "5;OL;Accordion;DirectRightOfCurrent;6",
      "5;OL;Accordion;OpenInTabstackWithRelated;6",
      "5;OL;Accordion;RightOfCurrent;6",
      "5;OL;Dotted;AlwaysLast;7",
      "5;OL;Dotted;DirectRightOfCurrent;6",
      "5;OL;Dotted;OpenInTabstackWithRelated;6",
      "5;OL;Dotted;RightOfCurrent;6",
      "5;OL;Off;AlwaysLast;8",
      "5;OL;Off;DirectRightOfCurrent;6",
      "5;OL;Off;OpenInTabstackWithRelated;6",
      "5;OL;Off;RightOfCurrent;6",
      "5;OL;Substrip;AlwaysLast;7",
      "5;OL;Substrip;DirectRightOfCurrent;6",
      "5;OL;Substrip;OpenInTabstackWithRelated;6",
      "5;OL;Substrip;RightOfCurrent;6",
      "5;X;Accordion;AlwaysLast;8",
      "5;X;Accordion;DirectRightOfCurrent;6",
      "5;X;Accordion;OpenInTabstackWithRelated;6",
      "5;X;Accordion;RightOfCurrent;6",
      "5;X;Dotted;AlwaysLast;8",
      "5;X;Dotted;DirectRightOfCurrent;6",
      "5;X;Dotted;OpenInTabstackWithRelated;6",
      "5;X;Dotted;RightOfCurrent;6",
      "5;X;Off;AlwaysLast;8",
      "5;X;Off;DirectRightOfCurrent;6",
      "5;X;Off;OpenInTabstackWithRelated;6",
      "5;X;Off;RightOfCurrent;6",
      "5;X;Substrip;AlwaysLast;8",
      "5;X;Substrip;DirectRightOfCurrent;6",
      "5;X;Substrip;OpenInTabstackWithRelated;6",
      "5;X;Substrip;RightOfCurrent;6",
      "5;XL;Accordion;AlwaysLast;8",
      "5;XL;Accordion;DirectRightOfCurrent;6",
      "5;XL;Accordion;OpenInTabstackWithRelated;6",
      "5;XL;Accordion;RightOfCurrent;6",
      "5;XL;Dotted;AlwaysLast;8",
      "5;XL;Dotted;DirectRightOfCurrent;6",
      "5;XL;Dotted;OpenInTabstackWithRelated;6",
      "5;XL;Dotted;RightOfCurrent;6",
      "5;XL;Off;AlwaysLast;8",
      "5;XL;Off;DirectRightOfCurrent;6",
      "5;XL;Off;OpenInTabstackWithRelated;6",
      "5;XL;Off;RightOfCurrent;6",
      "5;XL;Substrip;AlwaysLast;8",
      "5;XL;Substrip;DirectRightOfCurrent;6",
      "5;XL;Substrip;OpenInTabstackWithRelated;6",
      "5;XL;Substrip;RightOfCurrent;6",
      "6;O;Accordion;AlwaysLast;7",
      "6;O;Accordion;DirectRightOfCurrent;7",
      "6;O;Accordion;OpenInTabstackWithRelated;7",
      "6;O;Accordion;RightOfCurrent;7",
      "6;O;Dotted;AlwaysLast;7",
      "6;O;Dotted;DirectRightOfCurrent;7",
      "6;O;Dotted;OpenInTabstackWithRelated;7",
      "6;O;Dotted;RightOfCurrent;7",
      "6;O;Off;AlwaysLast;8",
      "6;O;Off;DirectRightOfCurrent;7",
      "6;O;Off;OpenInTabstackWithRelated;7",
      "6;O;Off;RightOfCurrent;7",
      "6;O;Substrip;AlwaysLast;7",
      "6;O;Substrip;DirectRightOfCurrent;7",
      "6;O;Substrip;OpenInTabstackWithRelated;7",
      "6;O;Substrip;RightOfCurrent;7",
      "6;OL;Accordion;AlwaysLast;7",
      "6;OL;Accordion;DirectRightOfCurrent;7",
      "6;OL;Accordion;OpenInTabstackWithRelated;7",
      "6;OL;Accordion;RightOfCurrent;7",
      "6;OL;Dotted;AlwaysLast;7",
      "6;OL;Dotted;DirectRightOfCurrent;7",
      "6;OL;Dotted;OpenInTabstackWithRelated;7",
      "6;OL;Dotted;RightOfCurrent;7",
      "6;OL;Off;AlwaysLast;8",
      "6;OL;Off;DirectRightOfCurrent;7",
      "6;OL;Off;OpenInTabstackWithRelated;7",
      "6;OL;Off;RightOfCurrent;7",
      "6;OL;Substrip;AlwaysLast;7",
      "6;OL;Substrip;DirectRightOfCurrent;7",
      "6;OL;Substrip;OpenInTabstackWithRelated;7",
      "6;OL;Substrip;RightOfCurrent;7",
      "6;X;Accordion;AlwaysLast;8",
      "6;X;Accordion;DirectRightOfCurrent;7",
      "6;X;Accordion;OpenInTabstackWithRelated;7",
      "6;X;Accordion;RightOfCurrent;7",
      "6;X;Dotted;AlwaysLast;8",
      "6;X;Dotted;DirectRightOfCurrent;7",
      "6;X;Dotted;OpenInTabstackWithRelated;7",
      "6;X;Dotted;RightOfCurrent;7",
      "6;X;Off;AlwaysLast;8",
      "6;X;Off;DirectRightOfCurrent;7",
      "6;X;Off;OpenInTabstackWithRelated;7",
      "6;X;Off;RightOfCurrent;7",
      "6;X;Substrip;AlwaysLast;8",
      "6;X;Substrip;DirectRightOfCurrent;7",
      "6;X;Substrip;OpenInTabstackWithRelated;7",
      "6;X;Substrip;RightOfCurrent;7",
      "6;XL;Accordion;AlwaysLast;8",
      "6;XL;Accordion;DirectRightOfCurrent;7",
      "6;XL;Accordion;OpenInTabstackWithRelated;7",
      "6;XL;Accordion;RightOfCurrent;7",
      "6;XL;Dotted;AlwaysLast;8",
      "6;XL;Dotted;DirectRightOfCurrent;7",
      "6;XL;Dotted;OpenInTabstackWithRelated;7",
      "6;XL;Dotted;RightOfCurrent;7",
      "6;XL;Off;AlwaysLast;8",
      "6;XL;Off;DirectRightOfCurrent;7",
      "6;XL;Off;OpenInTabstackWithRelated;7",
      "6;XL;Off;RightOfCurrent;7",
      "6;XL;Substrip;AlwaysLast;8",
      "6;XL;Substrip;DirectRightOfCurrent;7",
      "6;XL;Substrip;OpenInTabstackWithRelated;7",
      "6;XL;Substrip;RightOfCurrent;7",
  });
}

std::set<std::string> InvokedByLinkClickSnapshot() {
  return std::set<std::string>({
      "0;Background;AlwaysLast;10",
      "0;Background;DirectRightOfCurrent;1",
      "0;Background;OpenInTabstackWithRelated;1",
      "0;Background;RightOfCurrent;1",
      "0;EmailLink;AlwaysLast;10",
      "0;EmailLink;DirectRightOfCurrent;1",
      "0;EmailLink;OpenInTabstackWithRelated;10",
      "0;EmailLink;RightOfCurrent;10",
      "0;EmailLinkBackground;AlwaysLast;10",
      "0;EmailLinkBackground;DirectRightOfCurrent;1",
      "0;EmailLinkBackground;OpenInTabstackWithRelated;10",
      "0;EmailLinkBackground;RightOfCurrent;10",
      "0;Html;AlwaysLast;10",
      "0;Html;DirectRightOfCurrent;1",
      "0;Html;OpenInTabstackWithRelated;1",
      "0;Html;RightOfCurrent;1",
      "2;Background;AlwaysLast;10",
      "2;Background;DirectRightOfCurrent;3",
      "2;Background;OpenInTabstackWithRelated;3",
      "2;Background;RightOfCurrent;3",
      "2;EmailLink;AlwaysLast;10",
      "2;EmailLink;DirectRightOfCurrent;3",
      "2;EmailLink;OpenInTabstackWithRelated;10",
      "2;EmailLink;RightOfCurrent;10",
      "2;EmailLinkBackground;AlwaysLast;10",
      "2;EmailLinkBackground;DirectRightOfCurrent;3",
      "2;EmailLinkBackground;OpenInTabstackWithRelated;10",
      "2;EmailLinkBackground;RightOfCurrent;10",
      "2;Html;AlwaysLast;10",
      "2;Html;DirectRightOfCurrent;3",
      "2;Html;OpenInTabstackWithRelated;3",
      "2;Html;RightOfCurrent;3",
      "5;Background;AlwaysLast;7",
      "5;Background;DirectRightOfCurrent;6",
      "5;Background;OpenInTabstackWithRelated;6",
      "5;Background;RightOfCurrent;6",
      "5;EmailLink;AlwaysLast;10",
      "5;EmailLink;DirectRightOfCurrent;7",
      "5;EmailLink;OpenInTabstackWithRelated;10",
      "5;EmailLink;RightOfCurrent;10",
      "5;EmailLinkBackground;AlwaysLast;10",
      "5;EmailLinkBackground;DirectRightOfCurrent;7",
      "5;EmailLinkBackground;OpenInTabstackWithRelated;10",
      "5;EmailLinkBackground;RightOfCurrent;10",
      "5;Html;AlwaysLast;7",
      "5;Html;DirectRightOfCurrent;6",
      "5;Html;OpenInTabstackWithRelated;6",
      "5;Html;RightOfCurrent;6",
  });
}

std::set<std::string> NewTabByCommandPosition() {
  return std::set<std::string>({
      "2;;AlwaysLast;10",
      "2;;DirectRightOfCurrent;3",
      "2;;OpenInTabstackWithRelated;3",
      "2;;RightOfCurrent;3",
      "2;COMMAND_NEW_TAB_LINK;AlwaysLast;10",
      "2;COMMAND_NEW_TAB_LINK;DirectRightOfCurrent;3",
      "2;COMMAND_NEW_TAB_LINK;OpenInTabstackWithRelated;3",
      "2;COMMAND_NEW_TAB_LINK;RightOfCurrent;3",
      "2;INFO_PAGE_TAG;AlwaysLast;10",
      "2;INFO_PAGE_TAG;DirectRightOfCurrent;3",
      "2;INFO_PAGE_TAG;OpenInTabstackWithRelated;10",
      "2;INFO_PAGE_TAG;RightOfCurrent;10",
      "5;;AlwaysLast;7",
      "5;;DirectRightOfCurrent;6",
      "5;;OpenInTabstackWithRelated;6",
      "5;;RightOfCurrent;6",
      "5;COMMAND_NEW_TAB_LINK;AlwaysLast;7",
      "5;COMMAND_NEW_TAB_LINK;DirectRightOfCurrent;6",
      "5;COMMAND_NEW_TAB_LINK;OpenInTabstackWithRelated;6",
      "5;COMMAND_NEW_TAB_LINK;RightOfCurrent;6",
      "5;INFO_PAGE_TAG;AlwaysLast;10",
      "5;INFO_PAGE_TAG;DirectRightOfCurrent;7",
      "5;INFO_PAGE_TAG;OpenInTabstackWithRelated;10",
      "5;INFO_PAGE_TAG;RightOfCurrent;10",
  });
}

std::set<std::string> TapFromSpeedDialPosition() {
  return std::set<std::string>({
      "0;;AlwaysLast;10",
      "0;;DirectRightOfCurrent;1",
      "0;;OpenInTabstackWithRelated;10",
      "0;;RightOfCurrent;10",
      "2;;AlwaysLast;10",
      "2;;DirectRightOfCurrent;3",
      "2;;OpenInTabstackWithRelated;10",
      "2;;RightOfCurrent;10",
      "5;;AlwaysLast;10",
      "5;;DirectRightOfCurrent;7",
      "5;;OpenInTabstackWithRelated;10",
      "5;;RightOfCurrent;10",
  });
}

std::set<std::string> NewTopLevelTab() {
  return std::set<std::string>({
      "2;COMMAND_NEW_TAB_OUTSIDE_GROUP;AlwaysLast;10",
      "2;COMMAND_NEW_TAB_OUTSIDE_GROUP;DirectRightOfCurrent;3",
      "2;COMMAND_NEW_TAB_OUTSIDE_GROUP;OpenInTabstackWithRelated;10",
      "2;COMMAND_NEW_TAB_OUTSIDE_GROUP;RightOfCurrent;10",
      "5;COMMAND_NEW_TAB_OUTSIDE_GROUP;AlwaysLast;10",
      "5;COMMAND_NEW_TAB_OUTSIDE_GROUP;DirectRightOfCurrent;7",
      "5;COMMAND_NEW_TAB_OUTSIDE_GROUP;OpenInTabstackWithRelated;10",
      "5;COMMAND_NEW_TAB_OUTSIDE_GROUP;RightOfCurrent;10",
  });
}

std::set<std::string> MoveSnapshotBasic() {
  return std::set<std::string>({
      "t0>t0;0-", "t0>t1;0a", "t0>t2;1a", "t0>t3;2b", "t0>t4;3b", "t0>t5;4-",
      "t0>t6;5c", "t0>t7;6c", "t0>t8;7-", "t0>t9;8-", "t1>t0;0-", "t1>t1;1a",
      "t1>t2;1a", "t1>t3;2a", "t1>t4;3b", "t1>t5;4a", "t1>t6;5a", "t1>t7;6c",
      "t1>t8;7a", "t1>t9;8-", "t2>t0;0-", "t2>t1;1a", "t2>t2;2a", "t2>t3;2a",
      "t2>t4;3b", "t2>t5;4a", "t2>t6;5a", "t2>t7;6c", "t2>t8;7a", "t2>t9;8-",
      "t3>t0;0-", "t3>t1;1b", "t3>t2;2a", "t3>t3;3b", "t3>t4;3b", "t3>t5;4b",
      "t3>t6;5b", "t3>t7;6c", "t3>t8;7b", "t3>t9;8-", "t4>t0;0-", "t4>t1;1b",
      "t4>t2;2a", "t4>t3;3b", "t4>t4;4b", "t4>t5;4b", "t4>t6;5b", "t4>t7;6c",
      "t4>t8;7b", "t4>t9;8-", "t5>t0;0-", "t5>t1;1a", "t5>t2;2a", "t5>t3;3b",
      "t5>t4;4b", "t5>t5;5-", "t5>t6;5c", "t5>t7;6c", "t5>t8;7-", "t5>t9;8-",
      "t6>t0;0-", "t6>t1;1c", "t6>t2;2a", "t6>t3;3c", "t6>t4;4b", "t6>t5;5c",
      "t6>t6;6c", "t6>t7;6c", "t6>t8;7c", "t6>t9;8-", "t7>t0;0-", "t7>t1;1c",
      "t7>t2;2a", "t7>t3;3c", "t7>t4;4b", "t7>t5;5c", "t7>t6;6c", "t7>t7;7c",
      "t7>t8;7c", "t7>t9;8-", "t8>t0;0-", "t8>t1;1a", "t8>t2;2a", "t8>t3;3b",
      "t8>t4;4b", "t8>t5;5-", "t8>t6;6c", "t8>t7;7c", "t8>t8;8-", "t8>t9;8-",
      "t9>t0;0-", "t9>t1;1a", "t9>t2;2a", "t9>t3;3b", "t9>t4;4b", "t9>t5;5-",
      "t9>t6;6c", "t9>t7;7c", "t9>t8;8-", "t9>t9;9-",
  });
}

std::set<std::string> MoveSnapshotOn() {
  return std::set<std::string>({
      "t0>t0;1-;-",  "t0>t1;1-;t1", "t0>t2;2a;t2", "t0>t3;3-;t3", "t0>t4;4b;t4",
      "t0>t5;5-;t5", "t0>t6;6-;t6", "t0>t7;7c;t7", "t0>t8;8-;t8", "t0>t9;9-;t9",
      "t1>t0;1-;t0", "t1>t1;2a;-",  "t1>t2;2a;t2", "t1>t3;3a;t3", "t1>t4;4b;t4",
      "t1>t5;5a;t5", "t1>t6;6a;t6", "t1>t7;7c;t7", "t1>t8;8a;t8", "t1>t9;9-;t9",
      "t2>t0;1-;t0", "t2>t1;2a;t1", "t2>t2;3a;-",  "t2>t3;3a;t3", "t2>t4;4b;t4",
      "t2>t5;5a;t5", "t2>t6;6a;t6", "t2>t7;7c;t7", "t2>t8;8a;t8", "t2>t9;9-;t9",
      "t3>t0;1-;t0", "t3>t1;2b;t1", "t3>t2;3a;t2", "t3>t3;4b;-",  "t3>t4;4b;t4",
      "t3>t5;5b;t5", "t3>t6;6b;t6", "t3>t7;7c;t7", "t3>t8;8b;t8", "t3>t9;9-;t9",
      "t4>t0;1-;t0", "t4>t1;2b;t1", "t4>t2;3a;t2", "t4>t3;4b;t3", "t4>t4;5b;-",
      "t4>t5;5b;t5", "t4>t6;6b;t6", "t4>t7;7c;t7", "t4>t8;8b;t8", "t4>t9;9-;t9",
      "t5>t0;1-;t0", "t5>t1;2-;t1", "t5>t2;3a;t2", "t5>t3;4-;t3", "t5>t4;5b;t4",
      "t5>t5;6-;-",  "t5>t6;6-;t6", "t5>t7;7c;t7", "t5>t8;8-;t8", "t5>t9;9-;t9",
      "t6>t0;1-;t0", "t6>t1;2c;t1", "t6>t2;3a;t2", "t6>t3;4c;t3", "t6>t4;5b;t4",
      "t6>t5;6c;t5", "t6>t6;7c;-",  "t6>t7;7c;t7", "t6>t8;8c;t8", "t6>t9;9-;t9",
      "t7>t0;1-;t0", "t7>t1;2c;t1", "t7>t2;3a;t2", "t7>t3;4c;t3", "t7>t4;5b;t4",
      "t7>t5;6c;t5", "t7>t6;7c;t6", "t7>t7;8c;-",  "t7>t8;8c;t8", "t7>t9;9-;t9",
      "t8>t0;1-;t0", "t8>t1;2-;t1", "t8>t2;3a;t2", "t8>t3;4-;t3", "t8>t4;5b;t4",
      "t8>t5;6-;t5", "t8>t6;7-;t6", "t8>t7;8c;t7", "t8>t8;9-;-",  "t8>t9;9-;t9",
      "t9>t0;1-;t0", "t9>t1;2-;t1", "t9>t2;3a;t2", "t9>t3;4-;t3", "t9>t4;5b;t4",
      "t9>t5;6-;t5", "t9>t6;7-;t6", "t9>t7;8c;t7", "t9>t8;9-;t8", "t9>t9;10-;-",

  });
}

}  // namespace vivaldi::test_snapshots
