# Copyright (c) 2023 Vivaldi Technologies AS. All rights reserved

import("//build/config/ios/rules.gni")

bundle_data_xcassets("appicons_assets") {
  catalog = "AppIcons.xcassets"
  sources = [
    # img_appicon_final
    "AppIcons.xcassets/img_appicon_final.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_final.imageset/official-dark.png",
    "AppIcons.xcassets/img_appicon_final.imageset/official.png",

    # img_appicon_burgundy
    "AppIcons.xcassets/img_appicon_burgundy.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_burgundy.imageset/burgundy-dark.png",
    "AppIcons.xcassets/img_appicon_burgundy.imageset/burgundy.png",

    # img_appicon_yellow
    "AppIcons.xcassets/img_appicon_yellow.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_yellow.imageset/yellow-dark.png",
    "AppIcons.xcassets/img_appicon_yellow.imageset/yellow.png",

    # img_appicon_softpink
    "AppIcons.xcassets/img_appicon_softpink.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_softpink.imageset/softpink-dark.png",
    "AppIcons.xcassets/img_appicon_softpink.imageset/softpink.png",

    # img_appicon_softpurple
    "AppIcons.xcassets/img_appicon_softpurple.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_softpurple.imageset/softpurple-dark.png",
    "AppIcons.xcassets/img_appicon_softpurple.imageset/softpurple.png",

    # img_appicon_softred
    "AppIcons.xcassets/img_appicon_softred.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_softred.imageset/softred-dark.png",
    "AppIcons.xcassets/img_appicon_softred.imageset/softred.png",

    # img_appicon_sand
    "AppIcons.xcassets/img_appicon_sand.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_sand.imageset/sand-dark.png",
    "AppIcons.xcassets/img_appicon_sand.imageset/sand.png",

    # img_appicon_sagegreen
    "AppIcons.xcassets/img_appicon_sagegreen.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_sagegreen.imageset/sagegreen-dark.png",
    "AppIcons.xcassets/img_appicon_sagegreen.imageset/sagegreen.png",

    # img_appicon_green
    "AppIcons.xcassets/img_appicon_green.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_green.imageset/green-dark.png",
    "AppIcons.xcassets/img_appicon_green.imageset/green.png",

    # img_appicon_coral
    "AppIcons.xcassets/img_appicon_coral.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_coral.imageset/coral-dark.png",
    "AppIcons.xcassets/img_appicon_coral.imageset/coral.png",

    # img_appicon_camo
    "AppIcons.xcassets/img_appicon_camo.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_camo.imageset/camo-dark.png",
    "AppIcons.xcassets/img_appicon_camo.imageset/camo.png",

    # img_appicon_aqua
    "AppIcons.xcassets/img_appicon_aqua.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_aqua.imageset/aqua-dark.png",
    "AppIcons.xcassets/img_appicon_aqua.imageset/aqua.png",

    # img_appicon_blueprint
    "AppIcons.xcassets/img_appicon_blueprint.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_blueprint.imageset/blueprint-dark.png",
    "AppIcons.xcassets/img_appicon_blueprint.imageset/blueprint.png",

    # img_appicon_community
    "AppIcons.xcassets/img_appicon_community.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_community.imageset/community-dark.png",
    "AppIcons.xcassets/img_appicon_community.imageset/community.png",

    # img_appicon_gradient
    "AppIcons.xcassets/img_appicon_gradient.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_gradient.imageset/gradient-dark.png",
    "AppIcons.xcassets/img_appicon_gradient.imageset/gradient.png",

    # img_appicon_gradient1
    "AppIcons.xcassets/img_appicon_gradient1.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_gradient1.imageset/gradient1-dark.png",
    "AppIcons.xcassets/img_appicon_gradient1.imageset/gradient1.png",

    # img_appicon_gradient2
    "AppIcons.xcassets/img_appicon_gradient2.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_gradient2.imageset/gradient2-dark.png",
    "AppIcons.xcassets/img_appicon_gradient2.imageset/gradient2.png",

    # img_appicon_gradient3
    "AppIcons.xcassets/img_appicon_gradient3.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_gradient3.imageset/gradient3-dark.png",
    "AppIcons.xcassets/img_appicon_gradient3.imageset/gradient3.png",

    # img_appicon_internal
    "AppIcons.xcassets/img_appicon_internal.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_internal.imageset/internal-dark.png",
    "AppIcons.xcassets/img_appicon_internal.imageset/internal.png",

    # img_appicon_japan
    "AppIcons.xcassets/img_appicon_japan.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_japan.imageset/japan-dark.png",
    "AppIcons.xcassets/img_appicon_japan.imageset/japan.png",

    # img_appicon_lgbtplus
    "AppIcons.xcassets/img_appicon_lgbtplus.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_lgbtplus.imageset/lgbtplus-dark.png",
    "AppIcons.xcassets/img_appicon_lgbtplus.imageset/lgbtplus.png",

    # img_appicon_matteblack
    "AppIcons.xcassets/img_appicon_matteblack.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_matteblack.imageset/matteblack-dark.png",
    "AppIcons.xcassets/img_appicon_matteblack.imageset/matteblack.png",

    # img_appicon_oldopera
    "AppIcons.xcassets/img_appicon_oldopera.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_oldopera.imageset/oldopera-dark.png",
    "AppIcons.xcassets/img_appicon_oldopera.imageset/oldopera.png",

    # img_appicon_pink
    "AppIcons.xcassets/img_appicon_pink.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_pink.imageset/pink-dark.png",
    "AppIcons.xcassets/img_appicon_pink.imageset/pink.png",

    # img_appicon_pride
    "AppIcons.xcassets/img_appicon_pride.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_pride.imageset/pride-dark.png",
    "AppIcons.xcassets/img_appicon_pride.imageset/pride.png",

    # img_appicon_snapshot
    "AppIcons.xcassets/img_appicon_snapshot.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_snapshot.imageset/snapshot-dark.png",
    "AppIcons.xcassets/img_appicon_snapshot.imageset/snapshot.png",

    # img_appicon_white
    "AppIcons.xcassets/img_appicon_white.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_white.imageset/white-dark.png",
    "AppIcons.xcassets/img_appicon_white.imageset/white.png",

    # img_appicon_wood
    "AppIcons.xcassets/img_appicon_wood.imageset/Contents.json",
    "AppIcons.xcassets/img_appicon_wood.imageset/wood-dark.png",
    "AppIcons.xcassets/img_appicon_wood.imageset/wood.png",
  ]
}
