# Copyright 2022 Vivaldi Technologies. All rights reserved.

import("//build/config/ios/rules.gni")

bundle_data_xcassets("vivaldi_toolbar_assets") {
  catalog = "VivaldiToolbarAssets.xcassets"
  sources = [
    # toolbar_back
    "VivaldiToolbarAssets.xcassets/toolbar_back.symbolset/Contents.json",
    "VivaldiToolbarAssets.xcassets/toolbar_back.symbolset/toolbar_back.svg",

    # toolbar_switcher
    "VivaldiToolbarAssets.xcassets/toolbar_switcher.symbolset/Contents.json",
    "VivaldiToolbarAssets.xcassets/toolbar_switcher.symbolset/toolbar_switcher.svg",

    # toolbar_switcher_stack
    "VivaldiToolbarAssets.xcassets/toolbar_switcher_stack.symbolset/Contents.json",
    "VivaldiToolbarAssets.xcassets/toolbar_switcher_stack.symbolset/toolbar_switcher_stack.svg",

    # toolbar_switcher_overflow
    "VivaldiToolbarAssets.xcassets/toolbar_switcher_overflow.symbolset/Contents.json",
    "VivaldiToolbarAssets.xcassets/toolbar_switcher_overflow.symbolset/toolbar_switcher_overflow.svg",

    # toolbar_forward
    "VivaldiToolbarAssets.xcassets/toolbar_forward.symbolset/Contents.json",
    "VivaldiToolbarAssets.xcassets/toolbar_forward.symbolset/toolbar_forward.svg",

    # toolbar_menu
    "VivaldiToolbarAssets.xcassets/toolbar_menu.imageset/Contents.json",
    "VivaldiToolbarAssets.xcassets/toolbar_menu.imageset/vivaldi_toolbar_menu.pdf",
    "VivaldiToolbarAssets.xcassets/toolbar_menu.imageset/vivaldi_toolbar_menu_dark.pdf",

    # toolbar_panel
    "VivaldiToolbarAssets.xcassets/toolbar_panel.symbolset/Contents.json",
    "VivaldiToolbarAssets.xcassets/toolbar_panel.symbolset/toolbar_panel.svg",

    # toolbar_more
    "VivaldiToolbarAssets.xcassets/toolbar_more.symbolset/Contents.json",
    "VivaldiToolbarAssets.xcassets/toolbar_more.symbolset/toolbar_more.svg",

    # toolbar_reload
    "VivaldiToolbarAssets.xcassets/toolbar_reload.symbolset/Contents.json",
    "VivaldiToolbarAssets.xcassets/toolbar_reload.symbolset/toolbar_reload.svg",

    # toolbar_home
    "VivaldiToolbarAssets.xcassets/toolbar_home.symbolset/Contents.json",
    "VivaldiToolbarAssets.xcassets/toolbar_home.symbolset/toolbar_home.svg",

    # toolbar_copy_link
    "VivaldiToolbarAssets.xcassets/toolbar_copy_link.symbolset/Contents.json",
    "VivaldiToolbarAssets.xcassets/toolbar_copy_link.symbolset/toolbar_copy_link.svg",

    # toolbar_paste
    "VivaldiToolbarAssets.xcassets/toolbar_paste.symbolset/Contents.json",
    "VivaldiToolbarAssets.xcassets/toolbar_paste.symbolset/toolbar_paste.svg",

    # toolbar_move_to_top
    "VivaldiToolbarAssets.xcassets/toolbar_move_to_top.symbolset/Contents.json",
    "VivaldiToolbarAssets.xcassets/toolbar_move_to_top.symbolset/toolbar_move_to_top.svg",

    # toolbar_move_to_bottom
    "VivaldiToolbarAssets.xcassets/toolbar_move_to_bottom.symbolset/Contents.json",
    "VivaldiToolbarAssets.xcassets/toolbar_move_to_bottom.symbolset/toolbar_move_to_bottom.svg",

    # toolbar_button_color
    "VivaldiToolbarAssets.xcassets/toolbar_button_color.colorset/Contents.json",

    # toolbar_button_color_light
    "VivaldiToolbarAssets.xcassets/toolbar_button_color_light.colorset/Contents.json",

    # toolbar_button_color_dark
    "VivaldiToolbarAssets.xcassets/toolbar_button_color_dark.colorset/Contents.json",

    # tab_toolbar_button_color_highlighted
    "VivaldiToolbarAssets.xcassets/tab_toolbar_button_color_highlighted.colorset/Contents.json",

    # tab_toolbar_button_color_highlighted_incognito
    "VivaldiToolbarAssets.xcassets/tab_toolbar_button_color_highlighted_incognito.colorset/Contents.json",
  ]
}
