import("//build/config/features.gni")
import("//build/config/locales.gni")
import("locale_list.gni")

_vivaldi_all_locales = vivaldi_platform_all_locales
vivaldi_supported_locales = vivaldi_platform_supported_locales

if (enable_pseudolocales) {
  vivaldi_supported_locales += pseudolocales
  _vivaldi_all_locales += pseudolocales
}

vivaldi_normalize_locale_remove = []
vivaldi_normalize_locale_add = []
foreach(_locale, vivaldi_supported_locales) {
  if (_locale == "ca@valencia") {
    vivaldi_normalize_locale_remove += [ _locale ]
    vivaldi_normalize_locale_add += [ "ca-valencia" ]
  }
}

platform_unsupported_locales = _vivaldi_all_locales - vivaldi_supported_locales

if (is_android) {
  platform_unsupported_locales = []
}

# Minimum set of supported locales is platform_pak_locales
_foo =
    platform_pak_locales + vivaldi_supported_locales - vivaldi_supported_locales
assert(_foo == [], "Missing locales ${_foo}")
# print("all locales: $all_chrome_locales")
# print("PLAT: $platform_pak_locales")
# print("VIVL: $vivaldi_supported_locales")
