import("//build/config/features.gni")
import("//build/config/locales.gni")
import("locale_list.gni")

_vivaldi_all_locales = vivaldi_platform_all_locales
vivaldi_supported_locales = vivaldi_platform_supported_locales

if (enable_pseudolocales) {
  vivaldi_supported_locales += pseudolocales
  _vivaldi_all_locales += pseudolocales
}

vivaldi_normalize_locale_remove = []
vivaldi_normalize_locale_add = []
foreach(_locale, vivaldi_supported_locales) {
  if (_locale == "ca@valencia") {
    vivaldi_normalize_locale_remove += [ _locale ]
    vivaldi_normalize_locale_add += [ "ca-valencia" ]
  }
}

platform_unsupported_locales = _vivaldi_all_locales - vivaldi_supported_locales

if (is_android) {
  platform_unsupported_locales = []
}

if (is_ios) {
  vivaldi_ios_bundle_locales = []
  vivaldi_ios_bundle_output_locales = []
  vivaldi_ios_extra_locales = []
  vivaldi_ios_extra_output_locales = []
  vivaldi_ios_app_output_locales = []

  _vivaldi_ios_supported_locales = vivaldi_supported_locales
  if (enable_pseudolocales) {
    _vivaldi_ios_supported_locales -= pseudolocales
  }

  foreach(_locale, _vivaldi_ios_supported_locales) {
    if (_locale == "en-US") {
      _output_locale = "en"
    } else if (_locale == "es-MX") {
      _output_locale = "es_419"
    } else if (_locale == "pt") {
      _output_locale = "pt_BR"
    } else {
      _output_locale = string_replace(_locale, "-", "_")
    }

    vivaldi_ios_bundle_locales += [ _locale ]
    vivaldi_ios_bundle_output_locales += [ _output_locale ]

    _extra_locale = []
    _extra_locale = [ _locale ] + platform_pak_locales - platform_pak_locales
    if (_extra_locale != []) {
      vivaldi_ios_extra_locales += [ _locale ]
      vivaldi_ios_extra_output_locales += [ _output_locale ]
    }
  }

  vivaldi_ios_app_output_locales =
      locales_as_apple_outputs + vivaldi_ios_extra_output_locales
}

# Minimum set of supported locales is platform_pak_locales
_foo =
    platform_pak_locales + vivaldi_supported_locales - vivaldi_supported_locales
assert(_foo == [], "Missing locales ${_foo}")
# print("all locales: $all_chrome_locales")
# print("PLAT: $platform_pak_locales")
# print("VIVL: $vivaldi_supported_locales")
