# Copyright (c) 2025 Vivaldi Technologies AS. All rights reserved

static_library("update") {
  if (!is_android) {
    sources = [
      "vivaldi_update_backend.cc",
      "vivaldi_update_backend.h",
      "vivaldi_update_backend_notifier.h",
      "vivaldi_update_model_observer.h",
      "vivaldi_update_service.cc",
      "vivaldi_update_service.h",
      "vivaldi_update_service_factory.cc",
      "vivaldi_update_service_factory.h",
    ]
    if (is_win) {
      sources += [
       "win/vivaldi_updater_win.h",
       "win/vivaldi_updater_win.cc",
      ]
    }

    configs += [
      "//vivaldi/gn/config:release_kind"
    ]

    deps = [
      "//chrome/common:buildflags",
      "//content/public/browser",
      "//rlz/buildflags",
      "//vivaldi/app:resources",
      "//vivaldi/prefs:prefs_strings",
      "//vivaldi/extensions/schema"
    ]
    if (is_win) {
      deps += [
        "//extensions/common:mojom",
        "//vivaldi/browser:init_sparkle",
        "//vivaldi/update_notifier/thirdparty/winsparkle/src:winsparkle",
      ]
    libs = ["comctl32.lib"]
    }
  }
}