# Copyright 2023 Vivaldi Technologies. All rights reserved.

source_set("vivaldi_toolbar") {
  sources = [
    "vivaldi_sticky_toolbar_view.h",
    "vivaldi_sticky_toolbar_view.mm",
    "vivaldi_toolbar_constants.h",
    "vivaldi_toolbar_constants.mm",
  ]

  deps = [
    "resources:vivaldi_toolbar_assets",
    "//base",
    "//ui/base",
  ]

  frameworks = [
    "UIKit.framework",
    "Foundation.framework",
  ]
}
