update_target("//chrome:dependencies") {
  public_deps += [ "//vivaldi/importer" ]
}

update_target("//chrome/browser:browser") {
  deps += [
    "//vivaldi/importer",
    "//vivaldi/importer:browser",
  ]
}

if (!is_android) {
  update_target("//chrome/common/importer:interfaces") {
    deps += [ "//vivaldi/importer:browser" ]
  }

  update_target("//chrome/utility:utility") {
    deps += [
      "//vivaldi/importer",
      "//vivaldi/importer:browser",
    ]
  }
}
