# Copyright (c) 2015-2017 Vivaldi Technologies AS. All rights reserved

update_target("//chrome/browser:browser") {
  public_deps += [
    "//vivaldi/ui",
  ]
  allow_circular_includes_from += [
    "//vivaldi/ui",
  ]
}

update_target("//chrome/browser/ui:ui") {
  public_deps += [
    "//vivaldi/components:tabs",
    "//vivaldi/prefs:prefs_files_generated",
    "//vivaldi/ui",
    "//vivaldi/vivaldi_account:vivaldi_account_manager_factory"
  ]
  allow_circular_includes_from += [
    "//vivaldi/ui",
  ]
}

update_target("//chrome/browser/ui/startup:impl") {
  configs += [
    "//vivaldi/gn/config:release_kind",
  ]
}

update_target("//chrome/browser/profiles:profile_util_impl") {
  sources += [
    "//vivaldi/ui/webui/nuke_profile_directory_utils.inc"
  ]
}
