import("//vivaldi/gn/config/features.gni")
import("//vivaldi/gn/config/product.gni")
import("//vivaldi/gn/config/version.gni")
import("//vivaldi/testing/testing.gni")
import("//build/config/compiler/pgo/pgo.gni")
import("//vivaldi/gn/config/signer_features.gni")

if (is_win) {
  import("//build/config/win/visual_studio_version.gni")
}

if (is_win || is_mac) {
  import("//vivaldi/installer/widevine.gni")
}

if (!is_android && !is_mac && !is_ios) {
  update_target("//chrome:chrome_initial") {
    if (is_win) {
      output_name = "initialexe/vivaldi"
    } else {
      output_name = "vivaldi"
    }
  }
}

if (is_win) {
  update_target("//chrome:chrome_dll") {
    output_name = "vivaldi"
  }

  update_target("//chrome:reorder_imports") {
    inputs = []
    outputs = []
    inputs = [
      "$root_out_dir/initialexe/vivaldi.exe",
    ]
    outputs = [
      "$root_out_dir/vivaldi.exe",
      "$root_out_dir/vivaldi.exe.pdb",
    ]
  }

  update_target("//chrome/chrome_elf:chrome_elf") {
    output_name = "vivaldi_elf"
  }

  update_template_instance(
      "//chrome/app/version_assembly:version_assembly_manifest") {
    output = "$root_build_dir/$vivaldi_version_full.manifest"
  }

  if (vivaldi_build_tests) {
    update_template_instance("//chrome/test:browser_tests") {
      data_deps -= [
        "//chrome/browser/extensions/api:native_messaging_test_echo_&_host"
      ]
    }
  }

  update_template_instance("//chrome:chrome_dll_version") {
    sources -= ["app/chrome_dll.ver"]
    sources += [
      "//vivaldi/app/other_resources/vivaldi_dll.ver"
    ]
  }

  update_template_instance("//chrome:chrome_exe_version") {
    sources -= ["app/chrome_exe.ver"]
    sources += [
      "//vivaldi/app/other_resources/vivaldi_exe.ver"
    ]
  }

  update_template_instance("//chrome/chrome_elf:chrome_elf_resources") {
    sources -= ["chrome_elf.ver"]
    sources += [
      "//vivaldi/app/other_resources/vivaldi_elf.ver"
    ]
  }
}

if (is_android) {
  update_template_instance("//chrome/android:chrome_public_apk") {
    apk_name = "Vivaldi.${vivaldi_version_full}"
    lint_baseline_file = "//chrome/android/expectations/lint-baseline.xml"
    lint_suppressions_file = "$root_gen_dir/vivaldi/android/merged_suppression.xml"
    lint_suppressions_dep = "//vivaldi/android:generate_merged_lint_suppression_file"
    not_needed([
      "lint_suppressions_dep",
      "lint_baseline_file",
      "lint_suppressions_file",
      ])
  }

  update_template_instance("//chrome/android:chrome_public_bundle") {
    bundle_name = "Vivaldi.${vivaldi_version_full}"
    if (!is_vivaldi_lynkco) {
      # enable_lint = true
    }
    lint_baseline_file = "//chrome/android/expectations/lint-baseline.xml"
    lint_suppressions_file = "$root_gen_dir/vivaldi/android/merged_suppression.xml"
    lint_suppressions_dep = "//vivaldi/android:generate_merged_lint_suppression_file"
    not_needed([
      "lint_suppressions_dep",
      "lint_baseline_file",
      "lint_suppressions_file",
      ])
  }
}

if (!is_ios) {
  update_template_instance("//chrome/app/vector_icons:chrome_vector_icons") {
    sources -= ["browser_logo.icon"]
    sources += ["//vivaldi/app/resources/vector_icons/browser_logo.icon"]
  }

  update_template_instance("//ui/message_center:message_center_vector_icons") {
    sources -= ["product.icon"]
    sources += ["//vivaldi/app/resources/message_center_vector_icons/product.icon"]
  }

  update_template_instance("//components/omnibox/browser:omnibox_vector_icons") {
    sources -= ["product.icon"]
    sources += ["//vivaldi/app/resources/vector_icons/product.icon"]
  }
}

if (vivaldi_build_tests) {
  update_template_instance("//chrome/test:browser_tests") {
    deps -= [
      "//chrome/browser/actor:browser_tests",
      "//chrome/browser/actor:test_support",
      "//chrome/browser/actor/ui:browser_tests",
      "//chrome/browser/extensions/api/pdf_viewer_private:browser_tests",
    ]
  }

  update_template_instance("//chrome/test:unit_tests") {
    deps -= [
      "//chrome/browser/contextual_cueing:unit_tests",
    ]
  }
}

update_template_instance("//components/vector_icons:components_vector_icons") {
  sources -= [
    "${branding_path_component}/product.icon",
    "${branding_path_component}/product_refresh.icon",
  ]
  sources += [
    "//vivaldi/app/resources/vector_icons/product.icon",
    "//vivaldi/app/resources/vector_icons/product_refresh.icon",
  ]
}
