# Copyright (c) 2025 Vivaldi Technologies AS. All rights reserved

static_library("ios") {
  sources = [
    "adblock_rule_service.cc",
    "adblock_rule_service.h",
  ]

  public_deps = [ "//vivaldi/components/ad_blocker/public/core" ]

  deps = [
    "//base",
    "//components/keyed_service/core",
    "//url",
  ]
}
