import("//vivaldi/app/resource_list.gni")
import("//vivaldi/gn/config/locales.gni")
import("//vivaldi/gn/config/product.gni")

import("//build/config/locales.gni")

update_target("//base:base") {
  if (!defined(sources)) {
    sources = []
  }
  sources += [
    "//vivaldi/app/vivaldi_apptools.cpp",
    "//vivaldi/app/vivaldi_apptools.h",
  ]
  if (!defined(allow_circular_includes_from)) {
    allow_circular_includes_from = []
  }
  allow_circular_includes_from += [ "//base:base_static" ]
}

update_target("//base:base_static") {
  sources += [
    "//vivaldi/app/vivaldi_constants.cc",
    "//vivaldi/app/vivaldi_constants.h",
  ]
  if (is_win) {
    sources += [
      "//vivaldi/update_notifier/update_notifier_switches.cc",
      "//vivaldi/update_notifier/update_notifier_switches.h",
    ]
  }
  if (!defined(deps)) {
    deps = []
  }
  deps += [ "//base:debugging_buildflags" ]
}

update_target("//base/version_info:version_info") {
  sources += [
    "//vivaldi/app/vivaldi_version_info.cc",
    "//vivaldi/app/vivaldi_version_info.h",
  ]
  if (!is_ios) {
    deps += [ "//vivaldi/prefs:prefs_files_generator" ]
  }

  configs += [ "//vivaldi/gn/config:release_kind" ]
}

if (current_toolchain == default_toolchain) {
  foreach(_target_config, CHROMIUM_VIVALDI_RESOURCE_LIST) {
    _target = _target_config[0]
    vivaldi_source = _target_config[1]
    _flags = {
    }
    _flags = _target_config[2]
    _use_locales = []
    _extra_outputs = []
    if (defined(_flags.pak_file_prefix)) {
      _pakext = "pak"
      if (defined(_flags.pak_file_extension)) {
        _pakext = _flags.pak_file_extension
      }
      _locale_prefix = ""
      _extra_locales = []
      if (defined(_flags.extra_locale)) {
        _extra_locales += _flags.extra_locale
      }
      _use_locales = vivaldi_supported_locales + _extra_locales -
                     _extra_locales + _extra_locales
      foreach(_locale, _use_locales + all_chrome_locales - all_chrome_locales) {
        _locale_prefix = ""
        _locale_postfix = "$_locale"
        if (defined(_flags.pak_file_locale_prefix)) {
          _prefix_locale = _locale
          if (_locale == "en-GB") {
            _prefix_locale = "en-rGB"
          } else if (_locale == "de-CH") {
            _prefix_locale = "de-rCH"
          } else if (_locale == "pt-BR") {
            _prefix_locale = "pt-rBR"
          } else if (_locale == "pt-PT") {
            _prefix_locale = "pt-rPT"
          } else if (_locale == "zh-TW") {
            _prefix_locale = "zh-rTW"
          } else if (_locale == "zh-CN") {
            _prefix_locale = "zh-rCN"
          } else if (_locale == "es-419") {
            _prefix_locale = "es-rUS"
          } else if (_locale == "es-PE") {
            _prefix_locale = "es-rPE"
          } else if (_locale == "he") {
            _prefix_locale = "iw"
          } else if (_locale == "id") {
            _prefix_locale = "in"
          } else if (_locale == "ja-KS") {
            _prefix_locale = "ja-rKS"
          } else if (_locale == "ca-valencia" || _locale == "ca@valencia") {
            _prefix_locale = "b+ca+valencia"
          }
          _locale_prefix = _flags.pak_file_locale_prefix + "${_prefix_locale}/"
          _locale_postfix = ""
        } else if (_locale == "ca-valencia" || _locale == "ca@valencia") {
          _locale_postfix = "ca-valencia"
        }
        foreach(_gender_suffix, gender_suffixes) {
          _extra_outputs += [ _locale_prefix + _flags.pak_file_prefix +
                              "${_locale_postfix}${_gender_suffix}.${_pakext}" ]
        }
      }
    }
    _extra_inputs = []
    _have_strings =
        !defined(_flags.have_strings_flag) || _flags.have_strings_flag
    if (_have_strings) {
      assert(defined(_flags.translation_dir_setting))
      assert(defined(_flags.pak_file_prefix))
      if (defined(_flags.vivaldi_translation_dir_setting)) {
        _vivaldi_translation_dir = _flags.vivaldi_translation_dir_setting
      } else {
        _vivaldi_translation_dir = _flags.translation_dir_setting
      }
      _file_prefix = _flags.pak_file_prefix
      if (defined(_flags.string_file_prefix)) {
        _file_prefix = _flags.string_file_prefix
      }
      _vivaldi_file_prefix = "vivaldi_" + _file_prefix
      if (defined(_flags.vivaldi_file_prefix)) {
        _vivaldi_file_prefix = _flags.vivaldi_file_prefix
      }
      vivaldi_translations =
          get_path_info(vivaldi_source, "dir") +
          "/${_vivaldi_translation_dir}/${_vivaldi_file_prefix}"
    }

    _merge_extra_grit_defines = []
    if (defined(_flags.merge_extra_grit_defines)) {
      _merge_extra_grit_defines = _flags.merge_extra_grit_defines
    }

    update_template_instance(_target) {
      if (current_toolchain == default_toolchain) {
        if (defined(outputs)) {
          outputs += _extra_outputs
        }
      }
    }

    _grit_suffix = "_grit"
    if (is_android && defined(_flags.java_grd_name) && _flags.java_grd_name) {
      _grit_suffix = "_grit"
    } else if (!defined(_flags.have_strings_flag) || _flags.have_strings_flag ||
               (defined(_flags.use_strings_target) &&
                _flags.use_strings_target)) {
      _grit_suffix = "__strings_grit"
    }
    update_target(_target + _grit_suffix) {
      if (current_toolchain == default_toolchain) {
        inputs += [
                    vivaldi_source,
                    "//vivaldi/app/gritsettings/resource_ids",
                    "//vivaldi/app/resources/vivaldi_resources.py",
                  ] + _extra_inputs
        args += [
                  "--extra-input",
                  rebase_path(vivaldi_source, root_build_dir),
                  "--extra-resource-id",
                  rebase_path("//vivaldi/app/gritsettings/resource_ids",
                              root_build_dir),
                ] + extra_grit_defines + _merge_extra_grit_defines
      }
    }
  }
}
