import("//vivaldi/gn/config/features.gni")
import("//vivaldi/gn/config/locales.gni")
import("//vivaldi/gn/config/product.gni")
import("//vivaldi/gn/config/version.gni")
import("//vivaldi/app/resource_list.gni")

import("//build/config/locales.gni")

update_target("//chrome:visual_elements_resources") {
  sources = []
  sources += [
    "//vivaldi/app/other_resources/$VIVALDI_RELEASE_KIND/win8/Logo.png",
    "//vivaldi/app/other_resources/$VIVALDI_RELEASE_KIND/win8/SmallLogo.png",
    "//vivaldi/app/other_resources/vivaldi.VisualElementsManifest.xml",
  ]
}

update_target("//chrome/common:non_code_constants") {
  sources += [
    "//vivaldi/app/vivaldi_version_constants.cc",
    "//vivaldi/app/vivaldi_version_constants.h",
  ]
}

if (is_mac) {
  update_target("//chrome:chrome_app_icon") {
    sources -= [
      "app/theme/$branding_path_component/mac/app.icns",
    ]
    sources += [
      "//vivaldi/app/resources/theme/$VIVALDI_RELEASE_KIND/mac/app.icns",
    ]
  }

  update_target("//chrome:chrome_framework_resources") {
    sources -= [
      "app/theme/default_100_percent/$branding_path_component/product_logo_32.png",
    ]
    sources += [
      "//vivaldi/app/resources/theme/default_100_percent/$VIVALDI_RELEASE_KIND/product_logo_32.png",
    ]
  }

  update_target("//chrome:chrome_asset_catalog") {
    sources -= [
      "app/theme/$branding_path_component/mac/Assets.car",
    ]
    sources += [
      "//vivaldi/app/resources/theme/$VIVALDI_RELEASE_KIND/mac/Assets.car"
    ]
  }
}
